### ISSUE TITLE
Conversation notification of deleted user

### ISSUE THREAD

**Issue by R-J** [vanilla/vanilla#2364]
I received a spam message on vforg which I only knew because of the notification mail I received. The user and all his content (including that conversation) had already been deleted **before** my next visit in the forum. Since then, I had a "1 new message" alert for my inbox in the navigation bar. I could not make it disappear by myself. Only the next new message "cleared" the new message alert.

**Comment by linc** [comment]
I believe we fixed this.

**Comment by R-J** [comment]
It seems to be still a problem (or maybe again?) https://github.com/vanilla/vanilla/issues/2364
